routes:
  - exact: true
    path: ['/', '/main']
    component: StudioPage
    sitemap:
      changefreq: monthly
      priority: 1
      lastmod:
        - categories.uk.yml
        - app.uk.yml
  - path: /service/:id?
    component: ServicesPage
    provider: categories
    sitemap:
      changefreq: monthly
      priority: 1
  - path: /gallery/:id?
    component: GalleryPage
    provider: categories
    sitemap:
      changefreq: yearly
      priority: 0.7
  - path: /contacts
    component: ContactsPage
    sitemap:
      changefreq: monthly
      priority: 1
      lastmod:
        - app.uk.yml
