routes:
  - exact: true
    path: ['/', '/main']
    component: Studio
    sitemap:
      changefreq: monthly
      priority: 1
      lastmod:
        - categories.uk.yml
        - app.uk.yml
  - path: /service/:id?
    component: Services
    provider: categories
    sitemap:
      changefreq: monthly
      priority: 1
  - path: /gallery/:id?
    component: Gallery
    provider: categories
    sitemap:
      changefreq: yearly
      priority: 0.7
  - path: /contacts
    component: Contacts
    sitemap:
      changefreq: monthly
      priority: 1
      lastmod:
        - app.uk.yml
