name: Deploy to Github pages

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/main.yml
      - src/**/*
      - public/**/*
      - tools/**/*
      - '*.{js,json}'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
    env:
      PUBLIC_URL: /latest
      DOCS_ROOT: latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      env:
        cache-name: artedecor-deps
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: npm install
    - name: Build website
      env:
        NODE_ENV: production
      run: REACT_APP_COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA") npm run build
    - name: Build sitemap
      run: npm run build.sitemap
    - name: Pre-render
      run: npm run build.pages
    - name: Deploy
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_ACTOR: deploy-bot
      run: |
        cat <<- EOF > $HOME/.netrc
          machine github.com
          login $GITHUB_ACTOR
          password $GITHUB_TOKEN
          machine api.github.com
          login $GITHUB_ACTOR
          password $GITHUB_TOKEN
        EOF
        chmod 600 $HOME/.netrc
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git fetch origin gh-pages
        git checkout -f gh-pages
        rm -rf $DOCS_ROOT
        mv build $DOCS_ROOT
        git add $DOCS_ROOT
        git commit -m "chore(release): deploy ${DOCS_ROOT}"
        git push --set-upstream origin gh-pages
